// SPDX-FileCopyrightText: 2026 Lytheriia
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Erida.Discord.Linking;

[GenerateTypedNameReferences]
public sealed partial class DiscordLinkingWindow : DefaultWindow
{
    public DiscordLinkingWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
